### ISSUE TITLE
Error on ellmodulareqn calls

### ISSUE THREAD

**Issue by vinklein** [defeo/cypari2#40]
I got the following error when i call ellmodulareqn function.
Python version : 2.7
```
from cypari2 import Pari
pari = Pari()
pari.ellmodulareqn(2)
```

```
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    pari.ellmodulareqn(2)
  File "cypari2/auto_instance.pxi", line 7002, in cypari2.pari_instance.Pari_auto.ellmodulareqn (cypari2/pari_instance.c:50226)
  File "cypari2/handle_error.pyx", line 196, in cypari2.handle_error._pari_err_handle (cypari2/handle_error.c:2106)
PariError: error opening seadata file: `/usr/local/share/pari/seadata/sea2'
```

**Comment by jdemeyer** [comment]
Did you install the `seadata` files? See https://pari.math.u-bordeaux.fr/packages.html

**Comment by vinklein** [comment]
No i haven't. Thank you for the answer.

**Comment by vinklein** [comment]
Tested and it works.
