### ISSUE TITLE
Example G.galoissubfields(flag=2, v='z')[3] in cypari2.gen fails on mips architectures

### ISSUE THREAD

**Issue by tobihan** [defeo/cypari2#62]
Hi,

on Debian with pari 2.9.3 and python 2, this example fails on mips and mips64el (and maybe on mipsel, unclear because the testsuite crashes). The logs can be found at
https://buildd.debian.org/status/package.php?p=cypari2&suite=experimental

The error is:

    Testing cypari2.gen
    **********************************************************************
    File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_2.7/build/cypari2/gen.so", line ?, in cypari2.gen.__test__.Gen.galoissubfields (line 3780)
    Failed example:
        G.galoissubfields(flag=2, v='z')[3]
    Exception raised:
        Traceback (most recent call last):
          File "/usr/lib/python2.7/doctest.py", line 1315, in __run
            compileflags, 1) in test.globs
          File "<doctest cypari2.gen.__test__.Gen.galoissubfields (line 3780)[5]>", line 1, in <module>
            G.galoissubfields(flag=2, v='z')[3]
          File "cypari2/gen.pyx", line 3817, in cypari2.gen.Gen.galoissubfields
            sig_on()
          File "cypari2/handle_error.pyx", line 196, in cypari2.handle_error._pari_err_handle
            raise PariError(errnum, pari_error_string, new_gen_noclear(E))
        PariError: unknown type 64
    **********************************************************************

**Comment by jdemeyer** [comment]
1. Can you try PARI-2.9.4 or PARI master?

2. Can you try whether the example works in PARI/GP itself (without the cypari2 wrapper)?

3. Can some cypari2 developer get access to a test system to debug this?

**Comment by tobihan** [comment]
It also happens with pari 2.9.4, and also without the cypari2 wrapper. I reported it here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=889674

Bill Allombert has access to the mips porter boxes, maybe he'll have a look.

**Comment by jdemeyer** [comment]
> also without the cypari2 wrapper

So it's not a cypari2 bug.
